project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    right:
      - text: Posts
        href: /
      - about.qmd
      - cv.qmd
      - publications.qmd
  google-analytics: "G-XRSH8JDS68"
format:
  html:
    theme:
          light: flatly
          dark: darkly
    css: styles.css

editor: visual

